//
//  EngCollegeList.swift
//  EngStu
//
//  Created by Rohan Sakhare on 02/01/24.
//

import Foundation

let colleges = [
    "Dr.D.Y.Patil Institute of Technology, Pimpri",
    "College of Engineering Pune",
    "Abhinav Institute of Technology and Management - Hadapsar Campus",
    "ABMSP's Anantrao Pawar College of Engineering and Research",
    "Aeronautical Engineering and Research Organization - AERO",
    "Ahilyadevi Abhiyantriki Mahavidyalaya - Engineering College",
    "AISSMS Institute of Information Technology",
    "Ajeenkya DY Patil University",
    "Al-Ameen Educational and Medical Foundation College of Engineering and Management Institute - Courses",
    "Alard College of Engineering and Management",
    "All India Shri Shivaji Memorial Society's College of Engineering - AISSMS",
    "Army Institute of Technology - AIT",
    "Bharati Vidyapeeth Deemed University College of Engineering",
    "BITS Pilani, Pune Campus",
    "Bk Birla College of Engineering & Technology",
    "Cummins College of Engineering for Women",
    "Dapodi College of Engineering",
    "Defence Institute of Advanced Technology - DIAT",
    "Dhole Patil College of Engineering - DPCOE",
    "Dr. DY Patil Institute of Engineering & Innovation, Tathawade",
    "DY Patil College of Engineering",
    "DY Patil Technical Campus, Akurdi",
    "DnyanPrabodhini Institute of Engineering & Technology - DYPIT",
    "G. H. Raisoni College of Engineering & Management",
    "Genba Sopanrao Moze College Of Engineering",
    "Indian Institute of Science Education and Research, Pune",
    "International Institute of Information Technology, Pune",
    "Jagruti Education Society's Institute of Computer & Technology",
    "K.J. Somaiya College of Engineering",
    "Kavya Institute of Management & Engineering & Research",
    "MIT Academy of Engineering",
    "MIT College of Engineering, Pune",
    "MIT World Peace University",
    "Padmabhooshan Vasantdada Patil Institute of Technology - PVPIT",
    "PCCOE - Pimpri Chinchwad College of Engineering",
    "PCET - Pune Institute of Computer Education",
    "PES Modern College of Engineering",
    "Pune Vidyarthi Gruha's College of Engineering & Technology",
    "Rajarshi Shahu Maharaj Engineering College",
    "RMD Sinhagad School of Engineering",
    "Ryan Institute of Technology",
    "S.B. Jadhav College of Engineering & Technology",
    "Savitribai Phule Pune University",
    "Shri Chhatrapati Shivaji Maharaj College of Engineering",
    "Sinhgad Academy of Engineering",
    "Sinhgad College of Engineering",
    "Sinhgad Institute of Technology - SIT",
    "SK Patil College of Engineering & Technology",
    "Symbiosis Institute of Technology - SIT",
    "Trinity Academy of Engineering",
    "Trinity College of Engineering and Research",
    "VJTI - Veermata Jijabai Technological Institute",
    "Vishwakarma Institute of Information Technology - VIIT",
    "Vishwakarma Institute of Technology - VIT",
    "YCCE - Yashvantrao Chavan College of Engineering"
    ]
